# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-rabbit-mq
#   annotations:
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   tls:
#   - hosts:
#     - mq.kraeja.com
#     - admin.mq.kraeja.com
#     secretName: rabbit-mq-secret
#   rules:
#   - host: mq.kraeja.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           serviceName: rabbit-mq-cluster
#           servicePort: 5672
#   - host: admin.mq.kraeja.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           serviceName: rabbit-mq-cluster
#           servicePort: 15672